### ISSUE TITLE
Before Save and After Save event/Method

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#10]
Would be great if you can add two new public methods beforeSave & afterSave that can be overridden to perform any task before saving a model just like in Yii2 active record.
You can call the methods inside save()
and afterSave should be called only if the saving operation was successful.

**Comment by yidas** [comment]
Hi @razorsharpshady,

This feature is released from [version 2.14.0](https://github.com/yidas/codeigniter-model/releases/tag/2.14.0).

Cheers
Nick
