### ISSUE TITLE
Model's 'email' property returning CI_Email instance

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#13]
Model's `email` property returning CI_Email instance .
e.g
`
$this->load->model('yidas/user_model', 'userModel');
print_R($this->userModel->email); exit;
`

p.s email is a field that exist in table columns

**Comment by yidas** [comment]
Hi @razorsharpshady,

This issue has been solved from [version 2.16.0](https://github.com/yidas/codeigniter-model/releases/tag/2.16.0)

Thanks for your report.

Cheers
