### ISSUE TITLE
'is_unique' validation rule won't let me update data

### ISSUE THREAD

**Issue by imvision** [yidas/codeigniter-model#14]
I have set 'is_unique' rule in one of my models. It works great when adding new rows in db. But if I try to load and then save an existing row, I get the 'The name field must contain a unique value.'.

I think on update it should not throw this error unless a different row has violated this rule.

Is there any workaround for this?

**Comment by yidas** [comment]
Hi @imvision ,

Can you provide your code on this?

**Comment by imvision** [comment]
@yidas  This is the rule from Job_categories_model.php

`[
				'field' => 'name',
				'rules' => 'is_unique[job_categories.name]'
				// 'rules' => 'required',
				'errors' => [
					'required' => 'Title is required'
				]
]`

In my Controller I have an edit function and here is part of code from that:

`$category = $this->CategoryModel->findOne($id);

$category->min_hourly_pay = $min_rate;

if ($category->validate())
{
                    $status = $category->save(false);
                } else {
                    $mod_errors = $category->getErrors();
                    $error = implode('<br>', $mod_errors);
}`

On save I get the error 'name' must be unique. The validation checks the $category->name against all rows in the table. While it should check for all rows except where row->id != $category->id.

**Comment by yidas** [comment]
Hi @imvision,

`is_unique` is a limitation for model updating, you could define `is_unique` rule separately before insert, leaving this rule outside the model.

BTW, there is a fix for validation in [version 2.16.1](https://github.com/yidas/codeigniter-model/releases/tag/2.16.1)

Thanks for your advice.
Nick

**Comment by imvision** [comment]
Thank you.
