### ISSUE TITLE
Limit & Offset in Find All method

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#18]
Hi Nick, 
Currently the `findAll()` only takes in the query condition as a param but we cannot set **Limit** and **offset** for the active records. Would be great if you can add support for the record **limit+offset** so that not everyone have to override `findAll()` to get this basic functionality. 

btw Great work.

**Comment by yidas** [comment]
Hi @razorsharpshady,

`findAll()` is referred to Yii 2's method. Do you have the need for getting active records(ORM) by `find()`?

Thanks for advice!

**Comment by razorsharpshady** [comment]
Yes, something like this
`$customers = Customer::find()->where(['id' => 10])->limit(5)->offset(2)->all();`
to handle pagination.

**Comment by yidas** [comment]
Hi @razorsharpshady,

I have been added this feature in [Version 2.16.5](https://github.com/yidas/codeigniter-model/releases/tag/2.16.5). ([Document](https://github.com/yidas/codeigniter-model#findall))

Cheers
