### ISSUE TITLE
Reset write properties on save function

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#20]
Hi @yidas 
At line **1097**  why the `_writeProperties ` are emptied/resetted?
Is there any particular reason behind that ?

**Comment by yidas** [comment]
Hi @razorsharpshady,

Resetting `_writeProperties after saving for the next update changing.

**Comment by razorsharpshady** [comment]
Ok, But why `_writeProperties ` reset if the saving operation fails?

**Comment by yidas** [comment]
Hi @razorsharpshady,

This issue has been fixed from [version 2.17.1](https://github.com/yidas/codeigniter-model/releases/tag/2.17.1)

Thank you!
