### ISSUE TITLE
form validation pass through model

### ISSUE THREAD

**Issue by rupsk1607** [yidas/codeigniter-model#22]
I am using Jquery validation plugins for client-side validation in CodeIgniter and Server side using form_validation class. 

Same as yii2 and laravel cant we use validation define in model for both client side and server side?

**Comment by yidas** [comment]
Hi @rupsk1607,

codeigniter-model provides [Validation](https://github.com/yidas/codeigniter-model#validation) for model with error message setting, but you need to implement the client side validation interface based on server side validation.
