### ISSUE TITLE
CREATED_AT and UPDATED_AT aren't optimal at all.

### ISSUE THREAD

**Issue by indrakaw** [yidas/codeigniter-model#26]
On both of `CREATED_AT` and `UPDATED_AT`, it said:
```
    /**
     * @string Feild name for created_at, empty is disabled.
     */
```
But in reality they don't work that way. You may test it yourself by set them empty or either one. Eg. there will be an error on model insertion and stuff.

**Comment by yidas** [comment]
@indrakaw,

Both "CREATED_AT" and "UPDATED_AT" with empty settings are worked fine. What problems have you encountered?

**Comment by indrakaw** [comment]
Yes, it worked fine. I was working a table relation called `book_label` that has no additional columns. There was an error on insertion. It seems I forgot to set the model's attributes, or _something_.

/closed
