### ISSUE TITLE
Undefined index when get property with values of null

### ISSUE THREAD

**Issue by sansanbgl** [yidas/codeigniter-model#29]
![image](https://user-images.githubusercontent.com/3112367/59421315-96a03b80-8df8-11e9-8ed1-6acc0fe2986b.png)

![image](https://user-images.githubusercontent.com/3112367/59421428-c2bbbc80-8df8-11e9-86b9-5ff8ca7d33f0.png)

It's happen when you access using array key, 
but when using as property it's ok

This is ok
`$item->description `

This is not
`$item['description']`

**Comment by yidas** [comment]
Hi,

Can you provide the usage code?
