### ISSUE TITLE
hasOne does not work with empty()

### ISSUE THREAD

**Issue by wlatt1991** [yidas/codeigniter-model#30]
hasOne does not work with empty(). The function always returns true.
Example: 
echo $object->hasOneObject->key; // 25
var_dump(empty($object->hasOneObject->key)); // true

**Comment by yidas** [comment]
Hi @wlatt1991,

This has been fixed at [version 2.18.2](https://github.com/yidas/codeigniter-model/releases/tag/2.18.2).

Thanks for your report.

**Comment by yidas** [comment]
Hi @wlatt1991,

Thank you for reporting the bug.

You can try the [version 2.18.3](https://github.com/yidas/codeigniter-model/releases/tag/2.18.3)
