### ISSUE TITLE
Unknown column error

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#31]
ORM should throw error when a property's value is assigned which doesn't exist. e.g 
`` 
$model->additional_info = 1;
$model->save(); ``

`additional_info` is not a property of the `$model`, and it should throw error when value is assigned to it. 
Database throws error about the wrong column name.
![er](https://user-images.githubusercontent.com/20279966/61103569-284ea780-a490-11e9-94a2-2131de9e1ddb.PNG)

I think `__set()` should be somewhat similar to `__get()` .

**Comment by yidas** [comment]
Hi @razorsharpshady,

This lib has a `__get()` schema check. But for performance reasons, I might not add check `__set()`.
I think setting a non-schema property is not necessary to cost another query.

Thanks for your advice.

**Comment by razorsharpshady** [comment]
Hi @yidas , Can you add a function get all writable(table columns) fields name array of a model? 
so that people can handle this issue.

**Comment by yidas** [comment]
Hi @razorsharpshady,

I will develop a switch whether use the property check for write.

Cheers.

**Comment by yidas** [comment]
Hi @razorsharpshady,

This feature is released from [version 2.19.0](https://github.com/yidas/codeigniter-model/releases/tag/2.19.0).

Cheers.
