### ISSUE TITLE
does it work for MS SQL?

### ISSUE THREAD

**Issue by ErwinIbrani** [yidas/codeigniter-model#34]
$this->Groupvendors_model->findOne(1);
and give me error query :
SELECT * FROM "group_vendor" WHERE "`group_vendor`"."`id`" = 1 ORDER BY 1 OFFSET 0 ROWS FETCH NEXT 1 ROWS ONLY

**Comment by yidas** [comment]
Hi @ErwinIbrani,

You can check why your sql statement has an 'ORDER BY 1` string that is not added by library or query builder.

**Comment by daniboyBr** [comment]
I have tested and get the same error but, I could observe tath

if you put directly the primaryKey and value as array

$this->Model->findOne(['table_id'=>1]);

the error does not appear and get the data normaly

but if you only put the value get error on MS SQL with sqlsrv

$this->Model->findOne(10)
