### ISSUE TITLE
VSCode hints on $this in Static Method

### ISSUE THREAD

**Issue by otengkwame** [yidas/codeigniter-model#38]
On line numbers 555 and 584 vscode hints that "$this can not be used in a static method" will this cause a PHP Error. If so then how do I fix this.

```php
<?php

//Line 555
$instance = (isset($this)) ? $this : new static;
$record = $instance->_findByCondition($condition)

//Line 584 
$instance = (isset($this)) ? $this : new static;
$query = $instance->_findByCondition($condition);

**Comment by yidas** [comment]
Hi @otengkwame,

Could you provide the actual error message or picture of your PHP?

**Comment by otengkwame** [comment]
This is an image that explains this issue:

![Screenshot from 2020-02-05 15-11-43](https://user-images.githubusercontent.com/3446150/74088602-081bb100-4a90-11ea-83ad-8a92ce5a8652.png)

Sorry for answering late.

**Comment by yidas** [comment]
Hi @otengkwame,

Sorry for the late reply.

I would like to use `$this` in static method because it can also support for common method callling, you could ignore this warning because it has an `isset` check.

Thanks!
