### ISSUE TITLE
Pagination support?

### ISSUE THREAD

**Issue by enix-app** [yidas/codeigniter-model#4]
I think will be usefull

**Comment by yidas** [comment]
Hi @enix-app,

You could use query builder's `offset()` and `limit()` from `find()`:
```php
$records = $this->Posts_model->find()
    ->offset(20)
    ->limit(10)
    ->get()
    ->result_array();
```

Cheers.

**Comment by enix-app** [comment]
This below what I mean:
```php
// results:
[
  'items' => (array), // current's data
  'current' => (number),
  'previous' => (number),
  'next' => (number),
  'last' => (number),
  'total_pages' => (number),
  'total_item' => (number)
]
```

Sorry for my English, thank you for fast response.

**Comment by yidas** [comment]
Hi @enix-app,

This could be implemented by pagination component but not model.

I know that the design pattern of [Codeigniter's Pagination](https://www.codeigniter.com/userguide3/libraries/pagination.html) does not meet my expectation, thus I prepared to build a [Pagination](https://github.com/yidas/php-pagination) Lib for Codeigniter, which would clearly distinguish page input and page info-provider.

The pattern would be like Yii2 Pagination integration.

> [Yii2 - Pagination represents information relevant to pagination of data items.](https://www.yiiframework.com/doc/api/2.0/yii-data-pagination)
