### ISSUE TITLE
ORM feature Save & Update

### ISSUE THREAD

**Issue by hrydi** [yidas/codeigniter-model#45]
Helloo & Thank you for this library,
I wanna ask something about ORM features
```php
$this->load->model('Posts_model');

$post = $this->Posts_model->findOne(1);
if ($post) {
    $post->title = 'New CI3';
    $result = $post->save();
}
```
At above scripts, is it really need to find record first for updating the records? I hope it can be just like this:
```php
$this->load->model('Posts_model');

$post = new Posts_model;
$post->id = 1;
$post->title = 'New CI3';
$result = $post->save();
```
Terima Kasih, :+1:

**Comment by oasin** [comment]
Your below example creates a new record instead

**Comment by hrydi** [comment]
> Your below example creates a new record instead

yes i know it, but i mean.
can we just set id (primary key table) with some value, then the ->save() method can update the record based on that id value
