### ISSUE TITLE
findOne error with postgresql

### ISSUE THREAD

**Issue by quydox** [yidas/codeigniter-model#46]
Hello bro,

Thank you for your library

I am using Postgresql

here is error:

Error Number:

ERROR: missing FROM-clause entry for table "`games`" LINE 3: WHERE "`games`"."`id`" = 2 ^

```
SELECT * FROM "games" WHERE "`games`"."`id`" = 2 LIMIT 1
```

I use findOne(id) function

Can you take a look on this problem?

Thanks,

**Comment by yidas** [comment]
Hi~

If the problem persists, please provide more details so that I can confirm, thanks!
