### ISSUE TITLE
data is deleted always appear for query or_like on soft delete

### ISSUE THREAD

**Issue by wscdn** [yidas/codeigniter-model#51]
hello sir, how can all the data not be displayed for soft delete with a query like below

return $this->find(true) 
        ->or_like('id', $q)
        ->or_like('username', $q) 
        ->or_like('password', $q) 
        ->or_like('email', $q) 
        ->or_like('fullname', $q) 
        ->or_like('phone', $q) 
        ->limit($limit, $start)
        ->order_by($column, $sort)
        ->get()
        ->result();
    }

in fact the above query shows all data including soft delete, thaks you

**Comment by yidas** [comment]
Please refer to the configuration guide:
https://github.com/yidas/codeigniter-model#soft-deleted
