### ISSUE TITLE
Example of accessing a related object (model)

### ISSUE THREAD

**Issue by ItsJustATypo** [yidas/codeigniter-model#6]
Hi,

I'm new to Eloquent and would like to use it in CodeIgniter.  Your project looks great!  In your documentation, I don't see examples of accessing **_related_** models, for example:  

     An Author has many Blog_posts. 
     A Blog_post can have many Comments.  
  
I would like to access related models, such as:  

    $author = $this->Author_model->findOne(1);  // retrieve the Author with id = 1
    $blog_posts = $author->blog_posts->comments->findAll();  // retrieve all Comments for all Blog_posts by this Author

Is this possible with your project?

Thank you

**Comment by yidas** [comment]
Hi @ItsJustATypo 

I'm glad to hear that you like!

I have added this issue into milestone.

Thanks for your suggestion.

**Comment by rupalgohel** [comment]
@yidas , I am also looking for above feature. It would be great if you implement this.

**Comment by yidas** [comment]
@ItsJustATypo @rupalgohel 

ORM Relationships feature is released from [version 2.14.0](https://github.com/yidas/codeigniter-model/releases/tag/2.14.0).

Cheers
Nick
