### ISSUE TITLE
Throw Property does not exist error if value is null

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#7]
ORM throws  Property does not exist error  if property's value is null in database.
I think you should add key exists check in function  **__get($name)** of Model.php (line 1351 & 1355) instead of isset. 
![error](https://user-images.githubusercontent.com/20279966/52550031-47bba880-2dfc-11e9-87ac-19ade50e1b1c.PNG)
BTW you did a really good job with this Project.

**Comment by yidas** [comment]
Hi @razorsharpshady,

Thank you for your great advice!

This issue has been fixed in the [version 2.12.1](https://github.com/yidas/codeigniter-model/releases/tag/2.12.1).

Cheers!
Nick Tsai

**Comment by razorsharpshady** [comment]
That was quick, Thanks for the fix.
