### ISSUE TITLE
Property does not exists

### ISSUE THREAD

**Issue by razorsharpshady** [yidas/codeigniter-model#8]
If I instantiate a new Model, and try to access the column values(which should should be empty), it throws **Property `id` does not exist** error.

Code example: 
$fileModel = new File_model();
if($fileModel->id){
echo 'Fixed';
}

**Comment by yidas** [comment]
Hi @razorsharpshady,

Thank you again for your great advice!

This issue has been fixed in the [version 2.12.2](https://github.com/yidas/codeigniter-model/releases/tag/2.12.2).

Cheers!
Nick Tsai

**Comment by razorsharpshady** [comment]
Thanks for the quick response. I checked the fix you implemented and I think it has a bug in it i.e we can access **even a non-existing property** 
Code example:
```
$fileModel = new File_model();
if($fileModel->anyRandomPropertyName){
echo 'THIS PROPERTY DOESNT EXIST BUT NO ERROR WAS THROWN';
}
```
I think you can use **SHOW COLUMNS**  like commands to set the list of properties available in a particular model class.

**Comment by yidas** [comment]
Hi @razorsharpshady,

Your usage reminds me to implement ORM Schema, this has been done at [version 2.13.0](https://github.com/yidas/codeigniter-model/releases/tag/2.13.0).

Thank you!
Nick

**Comment by razorsharpshady** [comment]
Thanks for the quick response & fix
